# Generated by Django 4.2.4 on 2023-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gstn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
