# Generated by Django 4.2.4 on 2024-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_customuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hub_status',
            field=models.BooleanField(default=False),
        ),
    ]
