# Generated by Django 4.2.4 on 2023-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_sellerdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdetails',
            options={'verbose_name_plural': 'Seller Details'},
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='account_holder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
