# Generated by Django 4.2.4 on 2023-09-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_sellerdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdetails',
            options={'verbose_name_plural': 'SellerDetails'},
        ),
    ]
