# Generated by Django 4.2.4 on 2023-09-07 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeapp', '0012_alter_sellerdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_details_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
