# Generated by Django 4.2.4 on 2023-09-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategory'},
        ),
    ]
