# Generated by Django 4.2.4 on 2023-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0018_product_status_product_stock_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_prefix',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
