# Generated by Django 4.2.4 on 2023-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0019_product_quantity_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_prefix',
            field=models.CharField(choices=[('gms', 'gms'), ('kg', 'kg')], default='gms', max_length=10),
        ),
    ]
