# Generated by Django 4.2.4 on 2023-09-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_alter_product_quantity_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_value',
        ),
    ]
