# Generated by Django 4.2.4 on 2023-10-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0024_cartitem_is_active_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
