# Generated by Django 4.2.4 on 2023-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0025_order_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_no',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
