# Generated by Django 4.2.4 on 2024-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0033_product_average_rating_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
