# Generated by Django 4.2.4 on 2024-02-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0037_farm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='name',
            new_name='farm_name',
        ),
    ]
