# Generated by Django 4.2.4 on 2024-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0038_rename_name_farm_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='visiting_hours',
        ),
        migrations.AddField(
            model_name='farm',
            name='visiting_hours_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='visiting_hours_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
