# Generated by Django 4.2.4 on 2024-02-22 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0041_farm_booking_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rooms_booked', models.PositiveIntegerField(default=1, null=True)),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('adults', models.PositiveIntegerField(default=0, null=True)),
                ('children', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
    ]
