# Generated by Django 4.2.4 on 2024-02-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0042_savebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebooking',
            name='farm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='storeapp.farm_booking'),
        ),
    ]
