# Generated by Django 4.2.4 on 2024-02-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0044_savebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
