# Generated by Django 4.2.4 on 2024-02-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0045_savebooking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_booking',
            name='seller',
        ),
        migrations.AddField(
            model_name='farm_booking',
            name='farm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeapp.farm'),
        ),
    ]
