# Generated by Django 4.2.4 on 2024-02-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0046_remove_farm_booking_seller_farm_booking_farm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
