# Generated by Django 4.2.4 on 2024-03-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0047_savebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebooking',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
