# Generated by Django 4.2.4 on 2024-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0049_savebooking_rooms_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='accepted_by_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
