# Generated by Django 4.2.4 on 2024-03-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0050_cartitem_accepted_by_store_cartitem_dispatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Requested', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
